AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: ETL For  XML service

Parameters:
  env:
    Type: String
    Default: staging
    AllowedValues:
      - dev
      - staging
      - prod
  app:
    Type: String
    Default: xml-parser-service

Mappings:
  EnviromentSettings:
    dev:
      LogLevel: DEBUG
      ProcessedDataBucket: "test-emile-dev"
      BUCKET: "test-emile-dev-sample"

    staging:
      LogLevel: DEBUG
      ProcessedDataBucket: ""
      BUCKET: ""

    prod:
      LogLevel: DEBUG
      ProcessedDataBucket: ""
      BUCKET: ""



Globals:
  Function:
    Layers:
      - !Ref XmlParserRequirementsLayer
    Tags:
      env: !Ref env
      service: !Ref app
    Environment:
      Variables:
        LOG_LEVEL: !FindInMap [ EnviromentSettings, !Ref env, LogLevel ]
        ENV: !Ref env
        PROCESSED_DATA_BUCKET: !FindInMap [ EnviromentSettings, !Ref env, ProcessedDataBucket ]

Resources:
  ApplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [!Ref env, "xml_parser_service"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - 'apigateway.amazonaws.com'
                - 'states.amazonaws.com'
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  S3BUCKET:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [ EnviromentSettings, !Ref env, BUCKET ]
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt XmlParserService.Arn

  XmlParserRequirementsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Join ["-", [!Ref env, "xml-parser-service-requirements"]]
      ContentUri: layers/
      CompatibleRuntimes:
        - python3.9

  XmlParserService:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Join ["_", [!Ref env, !Ref app, "xml_parser_service"]]
      Handler: xml_parser_service/main.handler
      Runtime: python3.9
      CodeUri: src/
      Description: "xml parser service lambda"
      MemorySize: 512
      Timeout: 800
      Role: !GetAtt ApplicationRole.Arn


  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt XmlParserService.Arn
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
      SourceAccount: !Ref 'AWS::AccountId'